apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: frontend

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    service: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      service: frontend
  template:
    metadata:
      labels:
        app: frontend
        service: frontend
    spec:
      serviceAccountName: frontend
      
      containers:
      - name: frontend-container
        image: hhana982/frontend:1.<version>
        ports:
        - containerPort: 80
        
        env: 